# Windows testing using Visual Studio.

# Syntax for this file:
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
  #- image: Visual Studio 2015
   # varProject: vs/simc_vs2015.vcxproj

# Disabled for now, MS Build not working properly with VS 2017
  - image: Visual Studio 2017
    varProject: vs/simc_vs2017.vcxproj
    
# fetch repository as zip archive
shallow_clone: true

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration: WebEngine


# Custom build Configuration, i.e. Debug, Release, etc.
build_script:
  - set "exepath=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe"
  - %exepath% %varProject% /maxcpucount

test_script:
  ## pass
    
after_test:
  ## pass
